### ISSUE TITLE
[Bug] Tabler icons missing?

### ISSUE THREAD

**Issue by adrienne** [Laravel-Backpack/theme-tabler#113]
I was trying to use Tabler icons from here https://tabler-icons.io/ with the Tabler theme, and they don't seem to be present? Are there plans to add those in?

**Comment by phpfour** [comment]
Hello,

The tabler icons are not included in the theme, but you can easily add them – follow [this](https://backpackforlaravel.com/docs/6.x/base-how-to#add-custom-css-to-all-admin-panel-pages) instructions to add the required CSS and then it should work. 

Thanks!

**Comment by tabacitu** [comment]
To answer your question @adrienne ... we don't plan to add Tabler Icons by default in the Tabler theme, no. Not in this version. Don't get me wrong, we like them too 😀 A lot. But we just couldn't squeeze in this feature in this release.

In the next Backpack version (next year) we might generalize icons too... so that each theme can use its individual icon pack... and then of course the Tabler theme would use Tabler icons.

But until then... all themes use the same icon pack, which is the one we used last year... Line Awesome.
